### ISSUE TITLE
[Query] Do we have to configure data sources again in this tool?

### ISSUE THREAD

**Issue by dilinisg** [wso2/identity-anonymization-tool#10]
**Description:**
In the datasources directory in the IS server, we configure different datasources we use. We have to configure the same under datsources directory in this tool as well. This is too much of configuration and duplication of the same. 

Therefore, can't we have an option to read the data sources from the IS directory without configuring it again here?

**Suggested Labels:**
Query, Improvement

**Affected Product Version:**
IS 550

**Comment by ruwanta** [comment]
No.
