### ISSUE TITLE
Need details on the arguments passed to run the tool

### ISSUE THREAD

**Issue by dilinisg** [wso2/identity-anonymization-tool#6]
**Description:**
Need details on the below arguments as to what they mean
`./forget-m -d <config-dir> -U <userName> [-D domainName] [-T tenantDomain]`

example: config-dir - what should be the config directory, the path to config directory etc.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
RuwanA

**Comment by ruwanta** [comment]
Added help message for arguments
https://github.com/wso2/identity-anonymization-tool/blob/master/components/org.wso2.carbon.privacy.forgetme.tool/src/main/resources/help.md
