### ISSUE TITLE
Grammar mistake in the logs

### ISSUE THREAD

**Issue by dilinisg** [wso2/identity-anonymization-tool#8]
**Description:**
Grammar mistake in the following log
`INFO  ForgetMeExecutionEngine:115 - All processors has been properly shut-down`

It should be "All processors have been properly shutdown"

**Suggested Labels:**
Bug

**Suggested Assignees:**
RuwanA

**Affected Product Version:**
IS 550

**Comment by ruwanta** [comment]
Fixed with commit 8c95c3dcc5647b26a546c534d912868243d6918b

Thanks.
